export default {
  GET_PACKAGES_SUCCESS: "GET_PACKAGES_SUCCESS",
  GET_PACKAGES_FAILED: "GET_PACKAGES_FAILED",
  GET_NO_PACKAGES: "GET_NO_PACKAGES",
  SORT_BY_NAME: "SORT_BY_NAME",
  SORT_BY_OWNER: "SORT_BY_OWNER",
  SORT_BY_STARS: "SORT_BY_STARS",
  GO_TO_PREV_PAG: "GO_TO_PREV_PAG",
  GO_TO_NEXT_PAG: "GO_TO_NEXT_PAG",
  SET_PAGE: "SET_PAGE"
}
